package BSWModuleDef.editor;

/*Generated by MPS */

import javax.swing.JButton;

public class CreateButton {

  public static JButton createGenerateDescriptionButton() {
    JButton generateBtn = new JButton("Generate");

    return generateBtn;
  }
}
