package BSWModuleDescription.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import java.util.Map;
import org.jetbrains.mps.openapi.language.SReferenceLink;
import jetbrains.mps.smodel.runtime.ReferenceConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.base.BaseReferenceConstraintsDescriptor;
import java.util.HashMap;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class ModuleValue_Constraints extends BaseConstraintsDescriptor {
  public ModuleValue_Constraints() {
    super(CONCEPTS.ModuleValue$Wj);
  }

  @Override
  protected Map<SReferenceLink, ReferenceConstraintsDescriptor> getSpecifiedReferences() {
    BaseReferenceConstraintsDescriptor d0 = new BaseReferenceConstraintsDescriptor(LINKS.definition$9oms, this, false, false) {};
    Map<SReferenceLink, ReferenceConstraintsDescriptor> references = new HashMap<SReferenceLink, ReferenceConstraintsDescriptor>();
    references.put(d0.getReference(), d0);
    return references;
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept ModuleValue$Wj = MetaAdapterFactory.getConcept(0xef22f920a15b4c66L, 0xa06ee0c4aea10605L, 0x95df5460e977f9eL, "BSWModuleDescription.structure.ModuleValue");
  }

  private static final class LINKS {
    /*package*/ static final SReferenceLink definition$9oms = MetaAdapterFactory.getReferenceLink(0xef22f920a15b4c66L, 0xa06ee0c4aea10605L, 0x95df5460e977f9eL, 0x95df5460e977ff2L, "definition");
  }
}
