package BSWModuleDef.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptAUTOSARDefs = createDescriptorForAUTOSARDefs();
  /*package*/ final ConceptDescriptor myConceptBooleanParameterDef = createDescriptorForBooleanParameterDef();
  /*package*/ final ConceptDescriptor myConceptChoiceContainerDef = createDescriptorForChoiceContainerDef();
  /*package*/ final ConceptDescriptor myConceptContainerDef = createDescriptorForContainerDef();
  /*package*/ final ConceptDescriptor myConceptDefCollection = createDescriptorForDefCollection();
  /*package*/ final ConceptDescriptor myConceptDefinitionsEntry = createDescriptorForDefinitionsEntry();
  /*package*/ final ConceptDescriptor myConceptEnumParameterDef = createDescriptorForEnumParameterDef();
  /*package*/ final ConceptDescriptor myConceptIntegerParameterDef = createDescriptorForIntegerParameterDef();
  /*package*/ final ConceptDescriptor myConceptModuleDef = createDescriptorForModuleDef();
  /*package*/ final ConceptDescriptor myConceptPackage = createDescriptorForPackage();
  /*package*/ final ConceptDescriptor myConceptParamConfContainerDef = createDescriptorForParamConfContainerDef();
  /*package*/ final ConceptDescriptor myConceptParameterDef = createDescriptorForParameterDef();
  /*package*/ final ConceptDescriptor myConceptRefereneceDef = createDescriptorForRefereneceDef();
  /*package*/ final ConceptDescriptor myConceptTextualParameterDef = createDescriptorForTextualParameterDef();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptAUTOSARDefs, myConceptBooleanParameterDef, myConceptChoiceContainerDef, myConceptContainerDef, myConceptDefCollection, myConceptDefinitionsEntry, myConceptEnumParameterDef, myConceptIntegerParameterDef, myConceptModuleDef, myConceptPackage, myConceptParamConfContainerDef, myConceptParameterDef, myConceptRefereneceDef, myConceptTextualParameterDef);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.AUTOSARDefs:
        return myConceptAUTOSARDefs;
      case LanguageConceptSwitch.BooleanParameterDef:
        return myConceptBooleanParameterDef;
      case LanguageConceptSwitch.ChoiceContainerDef:
        return myConceptChoiceContainerDef;
      case LanguageConceptSwitch.ContainerDef:
        return myConceptContainerDef;
      case LanguageConceptSwitch.DefCollection:
        return myConceptDefCollection;
      case LanguageConceptSwitch.DefinitionsEntry:
        return myConceptDefinitionsEntry;
      case LanguageConceptSwitch.EnumParameterDef:
        return myConceptEnumParameterDef;
      case LanguageConceptSwitch.IntegerParameterDef:
        return myConceptIntegerParameterDef;
      case LanguageConceptSwitch.ModuleDef:
        return myConceptModuleDef;
      case LanguageConceptSwitch.Package:
        return myConceptPackage;
      case LanguageConceptSwitch.ParamConfContainerDef:
        return myConceptParamConfContainerDef;
      case LanguageConceptSwitch.ParameterDef:
        return myConceptParameterDef;
      case LanguageConceptSwitch.RefereneceDef:
        return myConceptRefereneceDef;
      case LanguageConceptSwitch.TextualParameterDef:
        return myConceptTextualParameterDef;
      default:
        return null;
    }
  }


  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForAUTOSARDefs() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("BSWModuleDef", "AUTOSARDefs", 0xe303062338bb48cbL, 0xae7ef3be4cd83f0eL, 0x65c9ffa81d0f3d8fL);
    b.class_(false, false, false);
    b.origin("r:1dfccbdf-a5e4-4798-9d92-ff10e8880347(BSWModuleDef.structure)/7334674565656690063");
    b.version(2);
    b.property("shortname", 0x3430a1af27c758acL).type(PrimitiveTypeId.STRING).origin("3760683462513088684").done();
    b.property("multiplicity", 0x3430a1af27c758aeL).type(PrimitiveTypeId.INTEGER).origin("3760683462513088686").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForBooleanParameterDef() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("BSWModuleDef", "BooleanParameterDef", 0xe303062338bb48cbL, 0xae7ef3be4cd83f0eL, 0x3430a1af27c71f88L);
    b.class_(false, false, false);
    b.super_("BSWModuleDef.structure.ParameterDef", 0xe303062338bb48cbL, 0xae7ef3be4cd83f0eL, 0x3430a1af27c71ec6L);
    b.origin("r:1dfccbdf-a5e4-4798-9d92-ff10e8880347(BSWModuleDef.structure)/3760683462513074056");
    b.version(2);
    b.property("value", 0x3430a1af27c758bbL).type(PrimitiveTypeId.BOOLEAN).origin("3760683462513088699").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForChoiceContainerDef() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("BSWModuleDef", "ChoiceContainerDef", 0xe303062338bb48cbL, 0xae7ef3be4cd83f0eL, 0x65c9ffa81d0f3d02L);
    b.class_(false, false, false);
    b.super_("BSWModuleDef.structure.ContainerDef", 0xe303062338bb48cbL, 0xae7ef3be4cd83f0eL, 0x3430a1af27c71eabL);
    b.origin("r:1dfccbdf-a5e4-4798-9d92-ff10e8880347(BSWModuleDef.structure)/7334674565656689922");
    b.version(2);
    b.aggregate("choices", 0x65c9ffa81d0f3d48L).target(0xe303062338bb48cbL, 0xae7ef3be4cd83f0eL, 0x65c9ffa81d0f3d1eL).optional(true).ordered(true).multiple(true).origin("7334674565656689992").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForContainerDef() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("BSWModuleDef", "ContainerDef", 0xe303062338bb48cbL, 0xae7ef3be4cd83f0eL, 0x3430a1af27c71eabL);
    b.class_(false, false, false);
    b.super_("BSWModuleDef.structure.AUTOSARDefs", 0xe303062338bb48cbL, 0xae7ef3be4cd83f0eL, 0x65c9ffa81d0f3d8fL);
    b.origin("r:1dfccbdf-a5e4-4798-9d92-ff10e8880347(BSWModuleDef.structure)/3760683462513073835");
    b.version(2);
    b.aggregate("subContainers", 0x3430a1af27c71f82L).target(0xe303062338bb48cbL, 0xae7ef3be4cd83f0eL, 0x3430a1af27c71eabL).optional(true).ordered(true).multiple(true).origin("3760683462513074050").done();
    b.aggregate("parameters", 0x3430a1af27c71f84L).target(0xe303062338bb48cbL, 0xae7ef3be4cd83f0eL, 0x3430a1af27c71ec6L).optional(true).ordered(true).multiple(true).origin("3760683462513074052").done();
    b.aggregate("references", 0x65c9ffa81d0f3d4cL).target(0xe303062338bb48cbL, 0xae7ef3be4cd83f0eL, 0x3430a1af27c758a9L).optional(true).ordered(true).multiple(true).origin("7334674565656689996").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForDefCollection() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("BSWModuleDef", "DefCollection", 0xe303062338bb48cbL, 0xae7ef3be4cd83f0eL, 0x65c9ffa81d0f3d6eL);
    b.class_(false, false, false);
    b.super_("BSWModuleDef.structure.AUTOSARDefs", 0xe303062338bb48cbL, 0xae7ef3be4cd83f0eL, 0x65c9ffa81d0f3d8fL);
    b.origin("r:1dfccbdf-a5e4-4798-9d92-ff10e8880347(BSWModuleDef.structure)/7334674565656690030");
    b.version(2);
    b.aggregate("modules", 0x65c9ffa81d0f3d8aL).target(0xe303062338bb48cbL, 0xae7ef3be4cd83f0eL, 0x3430a1af27c71dc0L).optional(true).ordered(true).multiple(true).origin("7334674565656690058").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForDefinitionsEntry() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("BSWModuleDef", "DefinitionsEntry", 0xe303062338bb48cbL, 0xae7ef3be4cd83f0eL, 0x65c9ffa81d1af143L);
    b.class_(false, false, true);
    b.origin("r:1dfccbdf-a5e4-4798-9d92-ff10e8880347(BSWModuleDef.structure)/7334674565657456963");
    b.version(2);
    b.aggregate("packages", 0x65c9ffa81d1af15fL).target(0xe303062338bb48cbL, 0xae7ef3be4cd83f0eL, 0x3430a1af27c7586fL).optional(true).ordered(true).multiple(true).origin("7334674565657456991").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForEnumParameterDef() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("BSWModuleDef", "EnumParameterDef", 0xe303062338bb48cbL, 0xae7ef3be4cd83f0eL, 0x65c9ffa81d19a65bL);
    b.class_(false, false, false);
    b.super_("BSWModuleDef.structure.ParameterDef", 0xe303062338bb48cbL, 0xae7ef3be4cd83f0eL, 0x3430a1af27c71ec6L);
    b.origin("r:1dfccbdf-a5e4-4798-9d92-ff10e8880347(BSWModuleDef.structure)/7334674565657372251");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForIntegerParameterDef() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("BSWModuleDef", "IntegerParameterDef", 0xe303062338bb48cbL, 0xae7ef3be4cd83f0eL, 0x3430a1af27c71f87L);
    b.class_(false, false, false);
    b.super_("BSWModuleDef.structure.ParameterDef", 0xe303062338bb48cbL, 0xae7ef3be4cd83f0eL, 0x3430a1af27c71ec6L);
    b.origin("r:1dfccbdf-a5e4-4798-9d92-ff10e8880347(BSWModuleDef.structure)/3760683462513074055");
    b.version(2);
    b.property("value", 0x3430a1af27c758b9L).type(PrimitiveTypeId.INTEGER).origin("3760683462513088697").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForModuleDef() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("BSWModuleDef", "ModuleDef", 0xe303062338bb48cbL, 0xae7ef3be4cd83f0eL, 0x3430a1af27c71dc0L);
    b.class_(false, false, false);
    b.origin("r:1dfccbdf-a5e4-4798-9d92-ff10e8880347(BSWModuleDef.structure)/3760683462513073600");
    b.version(2);
    b.property("name", 0x65c9ffa81d1f3d38L).type(PrimitiveTypeId.STRING).origin("7334674565657738552").done();
    b.aggregate("contents", 0x3430a1af27c71f15L).target(0xe303062338bb48cbL, 0xae7ef3be4cd83f0eL, 0x65c9ffa81d0f3d8fL).optional(true).ordered(true).multiple(true).origin("3760683462513073941").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForPackage() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("BSWModuleDef", "Package", 0xe303062338bb48cbL, 0xae7ef3be4cd83f0eL, 0x3430a1af27c7586fL);
    b.class_(false, false, false);
    b.origin("r:1dfccbdf-a5e4-4798-9d92-ff10e8880347(BSWModuleDef.structure)/3760683462513088623");
    b.version(2);
    b.property("shortname", 0x65c9ffa81d0f3d6cL).type(PrimitiveTypeId.STRING).origin("7334674565656690028").done();
    b.aggregate("elements", 0x3430a1af27c75870L).target(0xe303062338bb48cbL, 0xae7ef3be4cd83f0eL, 0x3430a1af27c71dc0L).optional(true).ordered(true).multiple(true).origin("3760683462513088624").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForParamConfContainerDef() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("BSWModuleDef", "ParamConfContainerDef", 0xe303062338bb48cbL, 0xae7ef3be4cd83f0eL, 0x65c9ffa81d0f3d1eL);
    b.class_(false, false, false);
    b.super_("BSWModuleDef.structure.ContainerDef", 0xe303062338bb48cbL, 0xae7ef3be4cd83f0eL, 0x3430a1af27c71eabL);
    b.origin("r:1dfccbdf-a5e4-4798-9d92-ff10e8880347(BSWModuleDef.structure)/7334674565656689950");
    b.version(2);
    b.associate("choiceContainerDef", 0x65c9ffa81d0f3d3eL).target(0xe303062338bb48cbL, 0xae7ef3be4cd83f0eL, 0x65c9ffa81d0f3d02L).optional(true).origin("7334674565656689982").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForParameterDef() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("BSWModuleDef", "ParameterDef", 0xe303062338bb48cbL, 0xae7ef3be4cd83f0eL, 0x3430a1af27c71ec6L);
    b.class_(false, false, false);
    b.super_("BSWModuleDef.structure.AUTOSARDefs", 0xe303062338bb48cbL, 0xae7ef3be4cd83f0eL, 0x65c9ffa81d0f3d8fL);
    b.origin("r:1dfccbdf-a5e4-4798-9d92-ff10e8880347(BSWModuleDef.structure)/3760683462513073862");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForRefereneceDef() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("BSWModuleDef", "RefereneceDef", 0xe303062338bb48cbL, 0xae7ef3be4cd83f0eL, 0x3430a1af27c758a9L);
    b.class_(false, false, false);
    b.super_("BSWModuleDef.structure.AUTOSARDefs", 0xe303062338bb48cbL, 0xae7ef3be4cd83f0eL, 0x65c9ffa81d0f3d8fL);
    b.origin("r:1dfccbdf-a5e4-4798-9d92-ff10e8880347(BSWModuleDef.structure)/3760683462513088681");
    b.version(2);
    b.associate("destination", 0x95df5460e9bc3a2L).target(0xe303062338bb48cbL, 0xae7ef3be4cd83f0eL, 0x3430a1af27c71eabL).optional(true).origin("674965200417047458").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTextualParameterDef() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("BSWModuleDef", "TextualParameterDef", 0xe303062338bb48cbL, 0xae7ef3be4cd83f0eL, 0x65c9ffa81d19a63fL);
    b.class_(false, false, false);
    b.super_("BSWModuleDef.structure.ParameterDef", 0xe303062338bb48cbL, 0xae7ef3be4cd83f0eL, 0x3430a1af27c71ec6L);
    b.origin("r:1dfccbdf-a5e4-4798-9d92-ff10e8880347(BSWModuleDef.structure)/7334674565657372223");
    b.version(2);
    return b.create();
  }
}
