package BSWModuleDescription.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int AUTOSARVals = 0;
  public static final int ContainerValue = 1;
  public static final int ModuleValue = 2;
  public static final int NumericalParamValue = 3;
  public static final int ParameterValue = 4;
  public static final int ReferenceValue = 5;
  public static final int TextualParamValue = 6;
  public static final int ValCollection = 7;
  public static final int ValuesEntry = 8;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0xef22f920a15b4c66L, 0xa06ee0c4aea10605L);
    builder.put(0x65c9ffa81d0f3d8fL, AUTOSARVals);
    builder.put(0x95df5460e977fbaL, ContainerValue);
    builder.put(0x95df5460e977f9eL, ModuleValue);
    builder.put(0x95df5460e99b1ceL, NumericalParamValue);
    builder.put(0x95df5460e977fd6L, ParameterValue);
    builder.put(0x95df5460e99b1f7L, ReferenceValue);
    builder.put(0x95df5460e99b1b2L, TextualParamValue);
    builder.put(0x65c9ffa81d105b02L, ValCollection);
    builder.put(0x65c9ffa81d1af161L, ValuesEntry);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
