package BSWModuleDescription.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptAUTOSARVals = createDescriptorForAUTOSARVals();
  /*package*/ final ConceptDescriptor myConceptContainerValue = createDescriptorForContainerValue();
  /*package*/ final ConceptDescriptor myConceptModuleValue = createDescriptorForModuleValue();
  /*package*/ final ConceptDescriptor myConceptNumericalParamValue = createDescriptorForNumericalParamValue();
  /*package*/ final ConceptDescriptor myConceptParameterValue = createDescriptorForParameterValue();
  /*package*/ final ConceptDescriptor myConceptReferenceValue = createDescriptorForReferenceValue();
  /*package*/ final ConceptDescriptor myConceptTextualParamValue = createDescriptorForTextualParamValue();
  /*package*/ final ConceptDescriptor myConceptValCollection = createDescriptorForValCollection();
  /*package*/ final ConceptDescriptor myConceptValuesEntry = createDescriptorForValuesEntry();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
    deps.extendedLanguage(0xe303062338bb48cbL, 0xae7ef3be4cd83f0eL, "BSWModuleDef");
    deps.aggregatedLanguage(0xe303062338bb48cbL, 0xae7ef3be4cd83f0eL, "BSWModuleDef");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptAUTOSARVals, myConceptContainerValue, myConceptModuleValue, myConceptNumericalParamValue, myConceptParameterValue, myConceptReferenceValue, myConceptTextualParamValue, myConceptValCollection, myConceptValuesEntry);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.AUTOSARVals:
        return myConceptAUTOSARVals;
      case LanguageConceptSwitch.ContainerValue:
        return myConceptContainerValue;
      case LanguageConceptSwitch.ModuleValue:
        return myConceptModuleValue;
      case LanguageConceptSwitch.NumericalParamValue:
        return myConceptNumericalParamValue;
      case LanguageConceptSwitch.ParameterValue:
        return myConceptParameterValue;
      case LanguageConceptSwitch.ReferenceValue:
        return myConceptReferenceValue;
      case LanguageConceptSwitch.TextualParamValue:
        return myConceptTextualParamValue;
      case LanguageConceptSwitch.ValCollection:
        return myConceptValCollection;
      case LanguageConceptSwitch.ValuesEntry:
        return myConceptValuesEntry;
      default:
        return null;
    }
  }


  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForAUTOSARVals() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("BSWModuleDescription", "AUTOSARVals", 0xef22f920a15b4c66L, 0xa06ee0c4aea10605L, 0x65c9ffa81d0f3d8fL);
    b.class_(false, false, false);
    b.origin("r:327da334-76e6-4692-920d-0f681c8933c8(BSWModuleDescription.structure)/7334674565656690063");
    b.version(2);
    b.property("shortname", 0x3430a1af27c758acL).type(PrimitiveTypeId.STRING).origin("3760683462513088684").done();
    b.property("multiplicity", 0x3430a1af27c758aeL).type(PrimitiveTypeId.INTEGER).origin("3760683462513088686").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForContainerValue() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("BSWModuleDescription", "ContainerValue", 0xef22f920a15b4c66L, 0xa06ee0c4aea10605L, 0x95df5460e977fbaL);
    b.class_(false, false, false);
    b.super_("BSWModuleDescription.structure.AUTOSARVals", 0xef22f920a15b4c66L, 0xa06ee0c4aea10605L, 0x65c9ffa81d0f3d8fL);
    b.origin("r:327da334-76e6-4692-920d-0f681c8933c8(BSWModuleDescription.structure)/674965200416767930");
    b.version(2);
    b.associate("definition", 0x95df5460e99b182L).target(0xe303062338bb48cbL, 0xae7ef3be4cd83f0eL, 0x3430a1af27c71eabL).optional(true).origin("674965200416911746").done();
    b.aggregate("parameterValues", 0x95df5460e99b189L).target(0xef22f920a15b4c66L, 0xa06ee0c4aea10605L, 0x95df5460e977fd6L).optional(true).ordered(true).multiple(true).origin("674965200416911753").done();
    b.aggregate("referenceValues", 0x95df5460e99b1f2L).target(0xef22f920a15b4c66L, 0xa06ee0c4aea10605L, 0x95df5460e99b1f7L).optional(true).ordered(true).multiple(true).origin("674965200416911858").done();
    b.aggregate("subContainers", 0x95df5460e99b18cL).target(0xef22f920a15b4c66L, 0xa06ee0c4aea10605L, 0x95df5460e977fbaL).optional(true).ordered(true).multiple(true).origin("674965200416911756").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForModuleValue() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("BSWModuleDescription", "ModuleValue", 0xef22f920a15b4c66L, 0xa06ee0c4aea10605L, 0x95df5460e977f9eL);
    b.class_(false, false, false);
    b.super_("BSWModuleDescription.structure.AUTOSARVals", 0xef22f920a15b4c66L, 0xa06ee0c4aea10605L, 0x65c9ffa81d0f3d8fL);
    b.origin("r:327da334-76e6-4692-920d-0f681c8933c8(BSWModuleDescription.structure)/674965200416767902");
    b.version(2);
    b.associate("definition", 0x95df5460e977ff2L).target(0xe303062338bb48cbL, 0xae7ef3be4cd83f0eL, 0x3430a1af27c71dc0L).optional(true).origin("674965200416767986").done();
    b.aggregate("containers", 0x95df5460e99b186L).target(0xef22f920a15b4c66L, 0xa06ee0c4aea10605L, 0x95df5460e977fbaL).optional(true).ordered(true).multiple(true).origin("674965200416911750").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForNumericalParamValue() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("BSWModuleDescription", "NumericalParamValue", 0xef22f920a15b4c66L, 0xa06ee0c4aea10605L, 0x95df5460e99b1ceL);
    b.class_(false, false, false);
    b.super_("BSWModuleDescription.structure.ParameterValue", 0xef22f920a15b4c66L, 0xa06ee0c4aea10605L, 0x95df5460e977fd6L);
    b.origin("r:327da334-76e6-4692-920d-0f681c8933c8(BSWModuleDescription.structure)/674965200416911822");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForParameterValue() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("BSWModuleDescription", "ParameterValue", 0xef22f920a15b4c66L, 0xa06ee0c4aea10605L, 0x95df5460e977fd6L);
    b.class_(false, false, false);
    b.super_("BSWModuleDescription.structure.AUTOSARVals", 0xef22f920a15b4c66L, 0xa06ee0c4aea10605L, 0x65c9ffa81d0f3d8fL);
    b.origin("r:327da334-76e6-4692-920d-0f681c8933c8(BSWModuleDescription.structure)/674965200416767958");
    b.version(2);
    b.associate("definition", 0x95df5460e99b184L).target(0xe303062338bb48cbL, 0xae7ef3be4cd83f0eL, 0x3430a1af27c71ec6L).optional(true).origin("674965200416911748").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForReferenceValue() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("BSWModuleDescription", "ReferenceValue", 0xef22f920a15b4c66L, 0xa06ee0c4aea10605L, 0x95df5460e99b1f7L);
    b.class_(false, false, false);
    b.super_("BSWModuleDef.structure.AUTOSARDefs", 0xe303062338bb48cbL, 0xae7ef3be4cd83f0eL, 0x65c9ffa81d0f3d8fL);
    b.origin("r:327da334-76e6-4692-920d-0f681c8933c8(BSWModuleDescription.structure)/674965200416911863");
    b.version(2);
    b.associate("value", 0x95df5460e9ab9aaL).target(0xef22f920a15b4c66L, 0xa06ee0c4aea10605L, 0x95df5460e977fbaL).optional(true).origin("674965200416979370").done();
    b.associate("definition", 0x95df5460e9ab9acL).target(0xe303062338bb48cbL, 0xae7ef3be4cd83f0eL, 0x3430a1af27c758a9L).optional(true).origin("674965200416979372").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTextualParamValue() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("BSWModuleDescription", "TextualParamValue", 0xef22f920a15b4c66L, 0xa06ee0c4aea10605L, 0x95df5460e99b1b2L);
    b.class_(false, false, false);
    b.super_("BSWModuleDescription.structure.ParameterValue", 0xef22f920a15b4c66L, 0xa06ee0c4aea10605L, 0x95df5460e977fd6L);
    b.origin("r:327da334-76e6-4692-920d-0f681c8933c8(BSWModuleDescription.structure)/674965200416911794");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForValCollection() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("BSWModuleDescription", "ValCollection", 0xef22f920a15b4c66L, 0xa06ee0c4aea10605L, 0x65c9ffa81d105b02L);
    b.class_(false, false, false);
    b.super_("BSWModuleDef.structure.AUTOSARDefs", 0xe303062338bb48cbL, 0xae7ef3be4cd83f0eL, 0x65c9ffa81d0f3d8fL);
    b.origin("r:327da334-76e6-4692-920d-0f681c8933c8(BSWModuleDescription.structure)/7334674565656763138");
    b.version(2);
    b.aggregate("modules", 0x65c9ffa81d10b2dfL).target(0xef22f920a15b4c66L, 0xa06ee0c4aea10605L, 0x95df5460e977f9eL).optional(true).ordered(true).multiple(true).origin("7334674565656785631").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForValuesEntry() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("BSWModuleDescription", "ValuesEntry", 0xef22f920a15b4c66L, 0xa06ee0c4aea10605L, 0x65c9ffa81d1af161L);
    b.class_(false, false, true);
    b.origin("r:327da334-76e6-4692-920d-0f681c8933c8(BSWModuleDescription.structure)/7334674565657456993");
    b.version(2);
    b.aggregate("packages", 0x65c9ffa81d1af162L).target(0xe303062338bb48cbL, 0xae7ef3be4cd83f0eL, 0x3430a1af27c7586fL).optional(true).ordered(true).multiple(true).origin("7334674565657456994").done();
    return b.create();
  }
}
